### ISSUE TITLE
Set Up React Router

### ISSUE THREAD

**Issue by dongskyler** [Badwater-Apps/badwater-apps.github.io#1]

**Comment by tatar28** [comment]
> _ไม่มีคำอธิบาย_
https://github.com/Badwater-Apps/badwater-apps.github.io/issues/1#issue-611184291

**Comment by dongskyler** [comment]
> > _ไม่มีคำอธิบาย_
> > [#1 (comment)](https://github.com/Badwater-Apps/badwater-apps.github.io/issues/1#issue-611184291)

Sorry. What?
